#!/bin/bash -l

# Include your allocation number
#SBATCH -A XXXX-XX-XX

# Name your job
#SBATCH -J gmx_md

# Total number of nodes
#SBATCH --nodes=2

# Test run for 5 minutes
#SBATCH -t 00:05:00

#SBATCH -e error.log
#SBATCH -o output.log

# If you want to run on the Haswell nodes:
#SBATCH -C Haswell

# If you want to run on the Ivy Bridge nodes then
# remove the above "-C Haswell" line and load gromacs/2016.1-avx instead

MPIRUN_OPTIONS="-np 24"
module add gromacs/2016.1-avx2

mpirun $MPIRUN_OPTIONS gmx_mpi mdrun -s topol.tpr -deffnm gmx_md 
