#!/bin/bash -l

# Include your allocation number
#SBATCH -A XXXX-XX-XX

# Name your job
#SBATCH -J gmx_md

# Total number of nodes
#SBATCH --nodes=2

# Test run for 5 minutes
#SBATCH -t 00:05:00

#SBATCH -e error.log
#SBATCH -o output.log

# If you want to run on the Haswell nodes:
#SBATCH --gres=gpu:K80:1

# If you want to run on the Ivy Bridge nodes then
# remove the above --gres line and load gromacs/ 5.0.6-avx instead

MPIRUN_OPTIONS="-np 2"
module add gromacs/5.0.6-avx2

mpirun $MPIRUN_OPTIONS gmx_mpi mdrun -s topol.tpr -deffnm gmx_md 
