#/bin/bash

# we load the modules that we need
module add i-compilers/12.1.5 mkl/12.1.5 intelmpi/4.1.0 fftw/3.2.2-intel vasp/5.3.5

# start the mpd daemons: one on every compute node
NR_NODES=$(cat ${SP_HOSTFILE} | wc -l)
mpdboot -n ${NR_NODES} -f ${SP_HOSTFILE}

PROCS_PER_NODE=8
MPI_PROCS=$[NR_NODES*$PROCS_PER_NODE]

# now start the mpi application
# alternatively use vasp-gamma or vasp-noncollinear
mpiexec -n $MPI_PROCS vasp

# finally shutdown the mpd daemons
mpdallexit
