#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters"
    exit 1
fi

TARGET_DIR=$1/allinea-forge-config

mkdir -p $TARGET_DIR/allinea-forge-config
sed "s_REPLACEME_${TARGET_DIR}_g" /pdc/vol/allinea-forge/6.1/system.config.template > $TARGET_DIR/system.config
